### ISSUE TITLE
Websocket issues in debug output

### ISSUE THREAD

**Issue by marcvsnet** [aleibovici/cryptopump#42]
Seeing this issue in 1.8.0, 1.8.1 and 1.8.1.1 with Go 1.17.5. Maybe this is reason why my Binance funds are not reflected in the dashboard?

2021/12/17 10:33:55 http: panic serving 192.168.5.30:58941: runtime error: slice bounds out of range [:3] with length 0
goroutine 23 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0x913120, 0xc000029fe0})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/aleibovici/cryptopump/loader.LoadSessionDataAdditionalComponents(0x905cc0, 0xc0001f5860, 0x952ecb)
        /home/marcus/cryptopump/loader/loader.go:83 +0x12b2
main.(*myHandler).handler(0xc00000e2b8, {0xa05698, 0xc0000f4700}, 0xc0000f3400)
        /home/marcus/cryptopump/main.go:164 +0x597
net/http.HandlerFunc.ServeHTTP(0x0, {0xa05698, 0xc0000f4700}, 0x0)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0, {0xa05698, 0xc0000f4700}, 0xc0000f3400)
        /usr/local/go/src/net/http/server.go:2425 +0x149
net/http.serverHandler.ServeHTTP({0xc0001f57d0}, {0xa05698, 0xc0000f4700}, 0xc0000f3400)
        /usr/local/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc0001c4280, {0xa084e0, 0xc0000eb4a0})
        /usr/local/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3034 +0x4e8

websocket: bad handshake

**Comment by marcvsnet** [comment]
Thread count is also zero in 1.8.1.1, also no threads a logged in database like done before in 1.8.0

**Comment by aleibovici** [comment]
@marcvsnet It seems Cryptopump is complaining about your crypto symbol. What are you using in symbols? 
Here are some examples:  BTCBUSD, ETHBUSD, BTCUSDT, ETHUSDT.

**Comment by marcvsnet** [comment]
@aleibovici BTCUSDT is configured

I'm also seeing this in the cryptopump_debug.log

time="2021-12-17 11:03:54" level=debug msg="github.com/aleibovici/cryptopump/exchange.binanceGetSymbolFiatFunds - <APIError> code=-2014, msg=API-key format invalid." orderID=0 threadID=c6u610luae2hcrlh2b00
time="2021-12-17 11:03:55" level=debug msg="github.com/aleibovici/cryptopump/exchange.binanceGetSymbolFunds - <APIError> code=-2014, msg=API-key format invalid." orderID=0 threadID=c6u610luae2hcrlh2b00
time="2021-12-17 11:03:55" level=debug msg="main.execution - <APIError> code=-2014, msg=API-key format invalid." orderID=0 threadID=c6u610luae2hcrlh2b00
time="2021-12-17 11:03:56" level=debug msg="github.com/aleibovici/cryptopump/algorithms.WsUserDataServe - <APIError> code=-2014, msg=API-key format invalid." orderID=0 threadID=c6u610luae2hcrlh2b00

**Comment by aleibovici** [comment]
apikey and secret should not be quoted. Try removing the quotes as I see the log is complaining about invalid key.

**Comment by marcvsnet** [comment]
Just did that without luck. Still same messages. Any API restrictions that may prevent this from working? I'm using the config_default.yml and just added the api key and secret key to it. Now unquoted.

**Comment by aleibovici** [comment]
Was another config file created in the config directory? Normally it will create another one with the thread unique name. If so, make sure the api keys are there.

**Comment by marcvsnet** [comment]
ok, maybe just dump from my side, I moved the config_default.yml to config.yml and now it looks much better.

**Comment by marcvsnet** [comment]
Threads 0

is this an issue, as I could see 4 on v1.8.0

**Comment by marcvsnet** [comment]
seeing also this [Buy] Market data older than 100 seconds

**Comment by marcvsnet** [comment]
> @aleibovici seeing also this [Buy] Market data older than 100 seconds
> 
> cryptopump.log shows this
> 
> time="2021-12-17 11:57:02" level=info msg="github.com/aleibovici/cryptopump/exchange.binanceBuyOrder - code=-1013, msg=Filter failure: MIN_NOTIONAL" threadID=c6u6lpduae2gvoionkd0

Increasing the quantity seems to help come across this and thread count is also now 8.
