### ISSUE TITLE
Symbol ETHBUSD is not picked up

### ISSUE THREAD

**Issue by marcvsnet** [aleibovici/cryptopump#43]
Symbol ETHBUSD with Symbol FIAT BUSD is picked up from template file but reverts on startup to content of config.yml

**Comment by aleibovici** [comment]
@marcvsnet try setting it up manually in the config.yml file. the API keys also should be configured in config.yml. config_default.yml is only used to return settings to the original.

**Comment by marcvsnet** [comment]
@aleibovici  I found out, that even if I have multiple files in the config folder and select them via the dropbox, once I press the Start button, it defaults back to config.yml. Running a dedicated instance with a seperate database, where the config.yml contains the target config, works fine. Not sure if this is the intended way it should work.
